### ISSUE TITLE
微信小程序登录报错

### ISSUE THREAD

**Issue by dux-web** [tiantour/union#1]
引入包后报错 

2022/05/20 10:09:26 open conf.toml: no such file or directory
Usage of /Volumes/Web/guardian/tmp/main:
  -path string
        config file path (default "conf.toml")

放入空conf.toml 文件后 继续报错
2022/05/20 10:02:29 open cache err: dial tcp: missing address

**Comment by jiangyoucai** [comment]
因为要缓存token，所以引用了redis

请按如下步骤运行

1. 不要使用go run main.go运行
2. 先编译，再运行
   xyz -path conf.toml
 
  conf.toml
  ```
  [cache]
  ip = "your redis host"
  port = ":6379"
  ```

**Comment by jiangyoucai** [comment]
已发布v1.3.0版本，替换redis为ristretto
此版本无需导入配置文件
